### ISSUE TITLE
Codes are not running in Jupyter notebook 

### ISSUE THREAD

**Issue by rpc-3312** [MaayanLab/biojupies#110]
Two issues: 
1) After downloading using docker and opening, codes in the Jupyter notebook are not running properly The very first code to initialize notebook is showing this error: ERROR:root:File `'../library/v1.1.5/init.ipy.py'` not found. 
2) The notebook shows a preview of the dataset in section 1 but does not give any option to download it.

**Comment by ichobits** [comment]
same error on ubuntu 18.04

**Comment by ichobits** [comment]
ERROR:root:File `'../library/v1.1.5/init.ipy.py'` not found.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-7d6850761aa5> in <module>()
      1 # Initialize Notebook
      2 get_ipython().run_line_magic('run', '../library/v1.1.5/init.ipy')
----> 3 HTML('''<script> code_show=true;  function code_toggle() {  if (code_show){  $('div.input').hide();  } else {  $('div.input').show();  }  code_show = !code_show }  $( document ).ready(code_toggle); </script> <form action="javascript:code_toggle()"><input type="submit" value="Toggle Code"></form>''')

**Comment by u8sand** [comment]
Can you please try it with the image `maayanlab/biojupies-notebooks:v1.1.5` which I've just created? Sorry about this.. If this works I'll update the latest image.

**Comment by rpc-3312** [comment]
@u8sand Thanks much for your response. I just tried with the image you suggested, but the error still exists.

ERROR:root:File `'../library/v1.1.5/init.ipy.py'` not found.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-7d6850761aa5> in <module>()
      1 # Initialize Notebook
      2 get_ipython().run_line_magic('run', '../library/v1.1.5/init.ipy')
----> 3 HTML('''<script> code_show=true;  function code_toggle() {  if (code_show){  $('div.input').hide();  } else {  $('div.input').show();  }  code_show = !code_show }  $( document ).ready(code_toggle); </script> <form action="javascript:code_toggle()"><input type="submit" value="Toggle Code"></form>''')

NameError: name 'HTML' is not defined

**Comment by u8sand** [comment]
@rpc-3312 just to confirm:

`docker run -it -p 8888:8888 -v ${PWD}:/notebooks -e NOTEBOOK_UID=<NOTEBOOK_UID> maayanlab/biojupies-notebooks:v1.1.5`

Would be the new command you would execute.. somehow when I did it it worked.. can @ichobits check as well?

**Comment by rpc-3312** [comment]
@u8sand Yeah, now it works. Thanks so much!

**Comment by u8sand** [comment]
Okay the latest image has been updated.
