### ISSUE TITLE
Issue with google account ?

### ISSUE THREAD

**Issue by jrendu** [MaayanLab/biojupies#119]
I am trying to log with my google account but now there is an authorization error:

Erreur 400 : redirect_uri_mismatch
The redirect URI in the request, https://maayanlab.cloud/biojupies/login/google/authorized, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

I would be very pleased to be help

best regards

**Comment by u8sand** [comment]
This should now be fixed, thank you for reporting, sorry for the inconvenience.
