### ISSUE TITLE
Biojupies sign in problem

### ISSUE THREAD

**Issue by stefaniamantovani** [MaayanLab/biojupies#120]
Can you help me with this error?

Errore 400 : redirect_uri_mismatch
The redirect URI in the request, https://maayanlab.cloud/biojupies/login/google/authorized, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/${your_client_id}?project=${your_project_number}

thank you!

**Comment by u8sand** [comment]
This should now be fixed, thank you for reporting, sorry for the inconvenience.

**Comment by stefaniamantovani** [comment]
Hi,
my account has a new error that blocked my sign in:
500 error


Il giorno lun 1 mar 2021 alle ore 23:22 Daniel Clarke <
notifications@github.com> ha scritto:

**Comment by u8sand** [comment]
@stefaniamantovani   Sorry about this -- we've been having hardware issues in our local cluster and some apps have been harder to migrate than others (biojupies has a lot of dependencies as well).

This and many other issues we were observing should have been fixed today; please let us know if you run into any more issues.
