### ISSUE TITLE
Buttons to download the CSV files of the processed data and results

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#13]
Ability to download the raw reads per gene counts
Ability to download the normalized reads per gene
Ability to download the signature values for all genes
Ability to download the enrichment results
Ability to download the small molecule query results

**Comment by denis-torre** [comment]
Added buttons to download reads, metadata and signatures to [plugin release v0.7.3](https://github.com/MaayanLab/biojupies-plugins/tree/v0.7.3).
Enrichment and small molecule query results to follow soon.

**Comment by denis-torre** [comment]
Added buttins for enrichment and small molecule queries as of [v0.7.4](https://github.com/MaayanLab/biojupies-plugins/releases/tag/v0.7.4).
