### ISSUE TITLE
gene expression table 

### ISSUE THREAD

**Issue by jrendu** [MaayanLab/biojupies#131]
Is there a maximum size for uplaiding gene expression table ?

I haven't succeed to upload my files 

best regards 

john

**Comment by biowizz** [comment]
Same here. Even I am not able to upload my gene expression table. However, the example file works fine.
I signed out and tried without logging in. It did work once, but I am unable to upload the the same after logging in.
Thanks,
Sandeep

**Comment by u8sand** [comment]
Fixed in 0febedcb2ad8607865bc6eb6fda1e123b1f0dc91

If you're still having issues, please let us know. The max size should be around 30MB now.
