### ISSUE TITLE
BioJupies site times out when uploading some files

### ISSUE THREAD

**Issue by KMJ1618** [MaayanLab/biojupies#138]
When I try to upload certain files, BioJupies appears to upload the file, but then 'times out' by displaying a grey "X" icon to indicate a problem; refer to screenshot below. Once this grey X is displayed, no further action can be taken. This issue is preventing me from processing several files from several different studies.

I'll note that in the past, when I encountered this issue with large files, I had reduced the size of large files by removing all columns not involved in a particular single analysis, and that had allowed those smaller files to be successfully uploaded to BioJupies. However, for the attached .txt data file, there are many samples in both the Control and Perturbation groups for this single comparison, and there are no columns able to be removed from this dataset. Also note that, at 3 MB, this file isn't particularly large.

![image](https://user-images.githubusercontent.com/7283504/120032994-00578700-bfc9-11eb-961c-3bfcb59ad935.png)

[GSE163426_covidvsards.pcgenecounts_v3.txt](https://github.com/MaayanLab/biojupies/files/6562950/GSE163426_covidvsards.pcgenecounts_v3.txt)

**Comment by u8sand** [comment]
Fixed in 0febedcb2ad8607865bc6eb6fda1e123b1f0dc91
