### ISSUE TITLE
Unable to upload an Expression Table File.

### ISSUE THREAD

**Issue by githubtefo** [MaayanLab/biojupies#17]
Hi!

I am trying to upload an Expression Table File (.xlsx), but I get the following error:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>`
I tried several times with Firefox 57 and also with Chromium 67 using Linux.

Thank you!

**Comment by denis-torre** [comment]
Thank you for the feedback, @githubtefo - there was an issue loading .xlsx files which should now be fixed. Can you try uploading again?

**Comment by githubtefo** [comment]
thank you for your reply, @denis-torre. Now it works, thanks!
