### ISSUE TITLE
Landing page text edits

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#2]
Biojupies Automatically Generates
RNA-seq Data Analysis Notebooks
With BioJupies you can produce in seconds a customized, reusable, and interactive report from your own raw or processed RNA-seq data through a simple user interface

**Comment by denis-torre** [comment]
Updated accordingly and pushed to dev: [http://amp.pharm.mssm.edu/biojupies-dev/](http://amp.pharm.mssm.edu/biojupies-dev/).
