### ISSUE TITLE
Text edits to this page http://amp.pharm.mssm.edu/biojupies-dev/upload

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#3]
Raw FASTQ sample sequencing files generated from an RNA-seq profiling study

**Comment by denis-torre** [comment]
Updated accordingly and pushed to dev: [http://amp.pharm.mssm.edu/biojupies-dev/upload](http://amp.pharm.mssm.edu/biojupies-dev/upload)
