### ISSUE TITLE
Text edits to this page http://amp.pharm.mssm.edu/biojupies-dev/upload/reads

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#4]
Use the form below to upload raw RNA-seq data in FASTQ format. The files will be aligned to the reference genome to generate the quantified reads expression table at the gene level. The table will be subsequently made available for you to download and to generate the interactive notebook. Once you have uploaded the desired files, click Continue to proceed.

Upload Read Files
To begin, select the files you wish to upload using the form below, then click on Upload Files to proceed.

**Comment by denis-torre** [comment]
Updated accordingly and pushed to dev: [http://amp.pharm.mssm.edu/biojupies-dev/upload/reads](http://amp.pharm.mssm.edu/biojupies-dev/upload/reads)
