### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by denis-torre** [MaayanLab/biojupies#56]
- [x] Fix continue button on pages where scrolling is required
- [x] Predict wait time for analysis

**Comment by denis-torre** [comment]
Sticky scrolling 1dd3bca6f47b968f8c0f078c82223e20038acabb

**Comment by achtungmike** [comment]
Could you add a few more reference genomes to align to, such as saccharomyces cerevisiae and other model organisms?

**Comment by denis-torre** [comment]
Thanks for the suggestion - we are currently working on it. In the meantime, if you're interested in exploring pre-aligned RNA-seq data from other model organisms you can visit the ARCHS4 resource at https://amp.pharm.mssm.edu/archs4/archs4zoo.html
