### ISSUE TITLE
Files not uploading

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/biojupies#6]
Tried to upload 6 files... No progress... See screenshot. Using Windows and Chrome.
![biojupies-screenshot1](https://user-images.githubusercontent.com/12749033/40074897-f0f933c0-5848-11e8-922d-c74d8f8f735f.png)

**Comment by denis-torre** [comment]
I suspect this issue might be caused when uploading files from HTTP. Can you try again using HTTPS? [https://amp.pharm.mssm.edu/biojupies-dev/upload/reads](https://amp.pharm.mssm.edu/biojupies-dev/upload/reads)

**Comment by AviMaayan** [comment]
Yes. That works...

**Comment by lachmann12** [comment]
Add this script and it will not be an issue anymore:

if (location.protocol != 'https:'){    location.href = 'https:' +
window.location.href.substring(window.location.protocol.length);}
