### ISSUE TITLE
Clutergrammer Matrix

### ISSUE THREAD

**Issue by utkarsh-kapoor** [MaayanLab/biojupies#63]
Hi,

I uploaded a file with counts from 6 RNA Seq samples and number of rows is 700. I performed Differential Gene Expression profiling and also enabled Clustergrammer plugin. I have two issues:

1) Somehow, when I zoom into the heatmap, the Gene names have been appended with some kind of numbers (see attached screenshot)

2) When I download the matrix that clustergrammer generates, I see that it has much more number of rows than I provided. How does this happen?

Please advise

Thanks,

Utkarsh
![screenshot 2018-11-23 at 12 25 58 pm](https://user-images.githubusercontent.com/19148370/48941232-fd244180-ef1a-11e8-9390-db12c9e1cc00.png)

**Comment by denis-torre** [comment]
Hi Utkarsh,
Does the uploaded dataset have duplicate gene names on the rows? If so, this might be the cause of both issues.

In that case, I can collapse gene expression for duplicate gene symbols -  this should be an easy fix for the next release of the plugin library.

**Comment by utkarsh-kapoor** [comment]
Hi Denis,

I checked my list and there are indeed a couple of duplicate entries. I tried again removing them and it worked out fine. Thanks! It would be great however, it would be great if duplicates get collapsed.

Cheers,

Utkarsh
