### ISSUE TITLE
PCA plot not colouring different groups correctly

### ISSUE THREAD

**Issue by FloWuenne** [MaayanLab/biojupies#69]
Hi Biojupies developers,

first of all, Biojupies is a great tool and concept for the entire community, so thank you for developing such a resource! 

I am having an issue with the PCA plot implementation. When I upload any type of count matrix from my own data and I upload the corresponding metadata table, the PCA plot does not color the dots based on their groups. Additionally, when I hover over the points, the labels are all the same sample. I get the same issue when loading the example data count matrix and metadata that you provide under "Your data", which lets me believe its a general issue with the PCA plot implementation. The Clustergrammer shows all groups from the metadata table correctly though!

Thanks for your help with this,
Best,

Florian

**Comment by denis-torre** [comment]
Hi Florian,

Many thanks for the feedback - and apologies for the late reply.

At the moment, the PCA plugin colors the dots only if the user manually specifies groups using the provided text boxes. We are currently working on adding this feature when the user uploads a metadata table - this will require the user to specify which metadata column to color the samples with through the UI. This should be available soon.

In the meantime, you can [rerun the notebook](https://amp.pharm.mssm.edu/biojupies/docker) of interest and specify the column to color the points by using the `color_by="your_metadata_column"` parameter in the PCA function.

I tried reproducing the tooltip hovering issue, but was unsuccessful. If you could share a link to a notebook with the error I'd be happy to look into it. Thanks!

Denis

**Comment by FloWuenne** [comment]
Hi Denis,

thanks for your response. So as an example, I have just quickly created a notebook using the Example Dataset from the Biojupies homepage: [Example Data](https://amp.pharm.mssm.edu/biojupies/notebook/UtXk3iNLL)

I literally just clicked through the example to analyze data and took default parameters. When you hover over any point, the metadata shown is the same. 

Thanks for the tip on how to solve coloring issues at the moment by directly changing the code in the notebook!

Best,

Florian

**Comment by denis-torre** [comment]
Hi Florian,

Thank you for sharing the notebook. 9 out of the 12 samples indeed have the same "metastatic" and "melanoma cell line" metadata values. However, there is a small cluster of 3 samples on the right which belongs to the "normal primary melanocyte" group (GSM2344965, GSM2344966, GSM2344967). 

These samples are labeled differently on my end. Do the sample titles appear all the same as well? If so this might be caused by a Plotly browser compatibility issue.

Denis

**Comment by denis-torre** [comment]
Hi Florian,

I am glad to know things work correctly on your end.

You are right, I can see how the example notebook can be confusing. I will look into choosing a better dataset and default parameters to make it more intuitive.

Many thanks for the feedback!

Best,
Denis
