### ISSUE TITLE
"Edit in Chart Studio" option on plotly graphs does not load

### ISSUE THREAD

**Issue by Jx-b** [MaayanLab/biojupies#70]
Hi,

I created a notebook from existing GEO data and it seems that on plotly graphs, the option to "Edit in Chart Studio" does not work. When clicking on the icon, it opens a new tab (https://plot.ly/external#/) but never seems to load the data from the graph to edit.

**Comment by denis-torre** [comment]
Thanks for the feedback - apologies for the late reply. I tried reproducing this with an [example notebook](https://amp.pharm.mssm.edu/biojupies/notebook/UtXk3iNLL) on the latest versions of Chrome and Safari, but it seems to work correctly. Do you have a link to a notebook where you encounter this issue?

**Comment by Jx-b** [comment]
Hi, after checking, it seems it was due to blocked cookies, my bad... Thanks for the great work by the way, it is a great tool!
